### ISSUE TITLE
DCO introduction needs to be added

### ISSUE THREAD

**Issue by robekeane** [OpenDataology/OpenDataology#11]
DCO introduction needs to be added

**Comment by rgopikrishnan91** [comment]
Need to add credits wherever we use CC BY 4.0 license for documents. So I made some modifications and attached a fresh version of DCO here and attached as plain text file
[DCO.TXT](https://github.com/OpenDataology/OpenDataology/files/8666205/DCO.TXT)

**Comment by ZichengQu** [comment]
Added according to the comments, so close this issue.
