### ISSUE TITLE
COMMITTERS.csv needs to be updated documentation

### ISSUE THREAD

**Issue by ZichengQu** [OpenDataology/OpenDataology#20]

**Comment by rgopikrishnan91** [comment]
Some initial committers to be added
Gopi Krishnan Rajbahadur, <gopikrishnanrajbahadur@gmail.com>, Huawei, Canada
Jack Jiang, <zmjiang@gmail.com>, York University, Canada 
Daniel M. German, <dmg@uvic.ca>, University of Victoria, Canada
Dayi Lin, <heylindayi@gmail.com>, Huawei, Canada

**Comment by rgopikrishnan91** [comment]
All the initial committers have been added. So closing this issue
