### ISSUE TITLE
About the database 

### ISSUE THREAD

**Issue by Pateny** [OpenDataology/OpenDataology#34]
I have an advice about the database mentioned in Overview. I think if we allow the  visitors of the database to edit and modify the database, maybe this visitors  can help to check the licenses and may upload their analysis of new licenses, then the database can be expanded faster and those visitors can be the contributors.

**Comment by DoraHu-Grandall** [comment]
Why different repositories adopt different licenses? The MIT license is used in the OpenDataology repository. However, the Apache-2.0 license is used in the other repositories including metadata-API, portal-frontend, and license-generator.

**Comment by ZichengQu** [comment]
Thank you for your suggestion, which is a brilliant idea and makes it easier for more people to participate and contribute. We will consider it in the following work.
