### ISSUE TITLE
Different Licenses

### ISSUE THREAD

**Issue by DoraHu-Grandall** [OpenDataology/OpenDataology#36]
Why different repositories adopt different licenses? The MIT license is used in the OpenDataology repository. However, the Apache-2.0 license is used in the other repositories including metadata-API, portal-frontend, and license-generator.

**Comment by li-clement** [comment]
@DoraHu-Grandall Thanks, OpenDataology repository hosts all the documentation work. after lawyer's review, we need to change it to CC-BY SA 4.0.
