### ISSUE TITLE
Create a new repo for dataset tools API

### ISSUE THREAD

**Issue by zyt1024** [OpenDataology/OpenDataology#47]
**Is your feature request related to a problem? Please describe.**
The OpenDataology project should have an infrastructure repository, or a repository of tool services set, to store the various infrastructure or tool modules of the OpenDataology platform. 

**Describe the solution you'd like**
Now we have developed a new service for dataset review, which can be integrated into the dataset metadata and license-sharing platform. 

**Describe alternatives you've considered**
We will develop more tools, not just covering this dataset review service, so we wanna whether it is ok to create a new repository for us. Is it better to name this new repository as infrastructure, service-set, or any names better?

**Comment by rgopikrishnan91** [comment]
Maybe provide the proposed structure e.g., repostructure OpenDataology/tools/tool_name/ ?

**Comment by ZichengQu** [comment]
> Maybe provide the proposed structure e.g., repostructure OpenDataology/tools/tool_name/ ?

1. dataset compliance reviewer
2. dataset metadata uploader
3. dataset license uploader
4. SPDX license synchronizer
5. message notifier

Once this new repo is created, I will draw and upload a structure image of the tools in the repo README.md, and will update continuously.

**Comment by rgopikrishnan91** [comment]
Created. All repos have the following structure 

.config -- for config files
build -- for build files
res -- for all the resources such as images
dep -- for dependencies 
docs -- for documentation files
examples -- for illustrating examples 
src -- for the source code files 
test -- for the unit tests and test cases

**Comment by rgopikrishnan91** [comment]
Reopening the issue to make delete the folders under Opendataolgy/opendataogy and creating a repo under OpenDataology/

**Comment by rgopikrishnan91** [comment]
Created tools repo and the directory explanations are same as above
